version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install -g next
      - npm install -g typescript
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling code
      - yarn build
artifacts:
  files:
    - "**/*"
  base-directory: "frontend/.out"
