version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install -g next
      - npm install -g typescript
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling code
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: "frontend/.out"
