version: 0.2

env:
  parameter-store:
    RESEND_API_KEY: "/$PROJECT_NAME/$ENV/resend-api-key"

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install -g next
      - npm install -g typescript
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling code
      - export RESEND_API_KEY=${RESEND_API_KEY}
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: "frontend/out"
cache:
  paths:
    - "node_modules/**/*" # Cache `node_modules` for faster `yarn` or `npm i`
    - ".next/cache/**/*" # Cache Next.js for faster application rebuilds
